### ISSUE TITLE
React "import whatever.css" not supported.

### ISSUE THREAD

**Issue by j-windsor** [microsoft/angular-react#114]
This package seemingly only supports css-in-javascript styling for the react elements. Are there any plans to change that?

**Comment by bengry** [comment]
`@angular-react/core` isn't CSS-in-JS specific, it uses [`classnames`](https://www.npmjs.com/package/classnames) and [`stylenames`](https://www.npmjs.com/package/stylenames) under the hood, accepting them as `contentClass` and `contentStyle`, respectively.

`@angular-react/fabric`, in addition to supporting the above, also supports `[styles]` on all of it's components, which is CSS-in-JS, but that's due to the fact that [`office-ui-fabric-react`](https://github.com/OfficeDev/office-ui-fabric-react/) is [built that way](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Component-Styling#styles-prop).

You can still do something like this though:
```html
<fab-checkbox contentClass="my-class"></fab-checkbox> and it would just put `my-class` on the root child of the `<fab-checkbox>` DOM node.
```

You can read more about it [in the wiki](https://github.com/Microsoft/angular-react/wiki/Wrapper-libraries:-ReactWrapperComponent#restrictions).

**Comment by j-windsor** [comment]
I would like to wrap [azure-devops-ui](https://www.npmjs.com/package/azure-devops-ui) (which I could make as a contribution to this repo). Components in this package appear be css styled using typescript import statments that will be picked up by a bundler such as Webpack. For example, a line in Pill.js, representing the Pill component, is `import "Pill.css"`. Styling the wrapped React component that is styled using the ts `import` statement, to my knowledge, is not supported by `@angular-react/core` because it is reliant on the use of a bundler.

I am just wondering if there is any way you see this is possible through an update to the the core package. After some research, I am not convinced it is possible because I believe the `import` statment is reliant on a bundler and no particular angular feature. The best way I have thought of is to do a css `@import` of all the styles in a global stylesheet in the angular project.

**Comment by bengry** [comment]
You're correct - it relies on a bundle being used, or some other way of loading the css for these components.
Personally I'd suggest using Webpack for your Angular app, even if you're using the Angular CLI, it wraps Webpack, and if needed you can extend its configuration to add additional Webpack loaders or plugins.
Note that eirg CSS `@import`s, unless using a preprocessor like SASS, these issue requests, per `import` at runtime, which is suboptimal. Then you go back to using a loader for some preprocessor/PostCSS, so just your not gaining much abyway in this regard.

**Comment by bengry** [comment]
At any rate, feel free to make a PR adding `@angular-react/azure-devops` and the needed components (all of them or a subset). There further explanation on the Wiki, and you can use the Fabric project a s a reference.
