### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by egormiron** [Microsoft/angular-react#40]
Hello there! The page https://microsoft.github.io/angular-react/docs doesn't have any documentation now.
Does the documentation exist at all?  And if no, do you planning to add it in future?

**Comment by bengry** [comment]
Hey @egormiron, we're definitely not doing a very good job (or at all for that matter) in the documentation front at the moment.
This is something we'd like to do, but isn't prioritized too high at the moment (we do accept PRs though! 😄).

The code itself is pretty well documented though, especially for the more "interesting" stuff, which is `@angular-react/core`, so understanding what's going on (especially at the public api surface level) should be pretty easy.

For the `@angular-react/fabric` package - we try to stay as close as possible to the API that's exposed natively by the underlying `office-ui-fabric-react` package, with most changes being in casing of stuff (e.g. `ActionButton` -> `fab-action-button`), or transformations from render props to Angular `TemplateRef`s, `ComponentRef` or other alternatives.

Is there anything specific you're wondering about?

P.S.
There's also the `@angular-react/semantic-ui` package, which as the code shows - is pretty much dead, in the sense that it's not actively maintained or in active development. The original purpose of it was to keep us honest, especially in `@angular-react/core`, to being very UI framework agnostic, so we don't end up with coupling to Fabric where it shouldn't exist.
However, if anyone would like to submit a PR to add wrappers for it though (or any other component library), we're open to accepting them.

**Comment by bengry** [comment]
Reopening this since work on documentation has started. Some of it is in the code (see the [`docs` branch](https://github.com/Microsoft/angular-react/tree/docs)) and some in the [repository's wiki](https://github.com/Microsoft/angular-react/wiki). Note that most of it is a work-in-progress, but expect things to get better in the next few days.

If there are any contributions or comments on things we should cover etc. - feel free to mention me here and I'll see if we can cover that as part of our current documentation effort.

**Comment by bengry** [comment]
Closed by #101, as well as the wiki that's now in the repo, feel free to see there and re-open this if there's anything missing etc.

**Comment by samuelgoff** [comment]
> Reopening this since work on documentation has started. Some of it is in the code (see the [`docs` branch](https://github.com/Microsoft/angular-react/tree/docs)) and some in the [repository's wiki](https://github.com/Microsoft/angular-react/wiki). Note that most of it is a work-in-progress, but expect things to get better in the next few days.

> If there are any contributions or comments on things we should cover etc. - feel free to mention me here and I'll see if we can cover that as part of our current documentation effort.

Thanks so much for adding the wiki! This is a HUGE improvement 🙏🏼

However, @bengry the [`docs` branch](https://github.com/Microsoft/angular-react/tree/docs) is currently showing a 404:

<img width="1443" alt="Screen Shot 2019-06-28 at 2 02 26 PM" src="https://user-images.githubusercontent.com/2007084/60366493-4a84f780-99b1-11e9-9c06-cac783b0698a.png">

Further, if you follow the URLs from the main repo page to "[Documentation, quick start, and guides](https://microsoft.github.io/angular-react/)" the page is blank and there are a large number of console logs indicating 404 from resource requests:

<img width="1443" alt="Screen Shot 2019-06-28 at 2 32 51 PM" src="https://user-images.githubusercontent.com/2007084/60366628-ae0f2500-99b1-11e9-81e3-6d73c5b7e9d5.png">

**Comment by bengry** [comment]
@samuelgoff all docs are either in the code (JSDoc for the most part), as well as the repo's wiki - as you saw.
What was in the `docs` branch was migrated over to the repo wiki, so that's where you should mainly look.

Regarding the live example - I'm not sure what happened to it, looks like the CI build failed on something. Tagging @aarongreenwald  and @shaiRose, who are the active maintainers of this project. I'm no longer contributing to it, following me leaving Microsoft a few months ago. At any case, you should be able to clone the repo and do `npm run start:docs` (after the usual `npm install`) to check them out. There's nothing much there apart from some examples to show off performance and the like though, so I think your best bet is the repo wiki to get started with this project.
