### ISSUE TITLE
Components not rendering when using Fabric 0.5.11

### ISSUE THREAD

**Issue by jayserdny** [Microsoft/angular-react#89]
Hello,

I am trying to implement this library in a project. However, when using the 0.5.11 version of @angular-react/fabric, components do not render. I can render them but using the 0.1.6 version as it is done here: https://stackblitz.com/edit/angular-react. I cloned this same project and updated everything to the latest version and it stopped working. (I did update it locally)

Any clue?

**Comment by bengry** [comment]
The stackblitz you linked to is pretty old really - uses Angular 5 (we're on 7.1 and up at the moment) as well as very old versions of @angular-react and `office-ui-fabric-react` (5, we're at 6 now).

Can you share more details on what your versions in the app are? Mainly `@angular/*`, `office-ui-fabric-react` and you mentioned `@angular-react/fabric` is at 0.5.11, is `@angular-react/core` on the same version?

**Comment by jayserdny** [comment]
Both @angular-react/* are at the same version.

React, react-dom, and officd-ui-react are in the latest version.

If you need a project sample, I can provide one.

**Comment by bengry** [comment]
A project sample would be great. You didn't mention the Angular version itself (`@angular/core` etc.).
Also, we don't support `office-ui-fabric-react` at any version, since they sometimes introduce breaking changes in minor versions, from past experience, so we currently support only `6.110.0`, officially speaking. Other versions may work, but we don't support them, so YMMV.

**Comment by jayserdny** [comment]
Hello @bengry, here is a sample project: https://github.com/jayserdny/angular-react

**Comment by bengry** [comment]
Hey @jayserdny, I took a look at the repro - and there are a few of issues there:
1. You're using `fab-button`, which is not any of our exposed components. Note that with `@angular-react/fabric` we don't support props and components declared as legacy by `office-ui-fabric-react`, to reduce the maintenance overhead. So the API is a subset of the one of `office-ui-fabric-react`.
2. You used `label` instead of `text` on fabric buttons (there is no `label` prop in [their docs](https://developer.microsoft.com/en-us/fabric#/components/button)).
3. You can't use `style` on `fab-*` components (or any component that are `@angular-react/*`'s. If you do you'd get an error which prompts you to use `contentStyle` instead:
> ERROR Error: [fab-default-button] React wrapper components cannot have the 'style' attribute set. Use the following alternative: contentStyle.
They're essentially the same though (`[contentStyle]` actually accepts more then just plain strings, it uses [`stylenames`](https://www.npmjs.com/package/stylenames) under the hood), for your use-case. Same goes for `class` -> `contentClass` by the way.
4. You had a `key` input on the `fab-dialog`, which is both not-needed, and currently forbidden in `@angular-react`. This may change in the future - but again - it's unneeded.

Once I fixed all of these in the `app.component.html` (the rest of the code was untouched) I got this:
```html
<hello name="{{ name }}"></hello>
<p>
  Start editing to see some magic happen :)
</p>

<div>
  <fab-default-button text="Fabric [React] Button" (onClick)="toggleDialog()"></fab-default-button>
  <fab-dialog [hidden]="dialogHidden" (onDismiss)="toggleDialog()" key="d2" title="Fabric [React] Dialog" subText="Use Fabric React components inside your Angular app!" [type]="DialogType.normal">
    Hello world! {{ counter }}
    <fab-dialog-footer>
      <fab-default-button (onClick)="incrementCounter()" text='Save' contentStyle="margin-right:10px;"></fab-default-button>
      <fab-default-button (onClick)="toggleDialog()" text='Cancel'></fab-default-button>
    </fab-dialog-footer>
  </fab-dialog>
</div>
```

Any everything works :).

I'm closing the issue, but feel free to re-open if there's anything else.

**Comment by jayserdny** [comment]
Thanks, @bengry!!!!! I was using the same code from the one in the example so I didn't realize about the naming convention change :)
